### ISSUE TITLE
Possible bug in Person module related to work measures

### ISSUE THREAD

**Issue by rmertens** [lwillem/stride#2]
https://github.com/lwillem/stride/blob/5178c6cd2e9e76ff8a38c178b0dc0bef3c979aab/main/cpp/pop/Person.cpp#L80

should this be `isWorkplaceDistancingEnforced || IsTeleworking()` instead of `isWorkplaceDistancingEnforced && IsTeleworking()` ?

**Comment by lwillem** [comment]
Dear @rmertens, thank you for your message. In the population build up, we mark a given faction of the active population as eligible for telework in case social distancing measures are in place. As such, this option is activated to prevent people to be present at their workplace if workplace distancing is in place AND they are eligible for telework. So this statement is correct for our purpose, though I agree that the documentation might be sub-optimal.
